cookie:
  expiry_days: 30
  key: mtinventory_auth
  name: mtinventory_auth
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: "\uAD00\uB9AC\uC790"
      password: $2b$12$FHAoLSwlXeyedhqDNcU4yOdOjZRAD07eJyb6WA3J3aOyvi2EDhR9i
      role: admin
    user:
      email: user@example.com
      name: "\uC77C\uBC18 \uC0AC\uC6A9\uC790"
      password: $2b$12$XBkJfKQ.894M/CVbt9kYFuJD0ZH.HU/6X7affepztY.5TRYtdp6Ai
      role: user
